---
# tasks file for drupsible.twigc
- name: Make sure working directory exists
  file:
    path: "{{ twigc_composer_working_dir }}"
    state: directory

- name: Require Twig via composer
  composer:
    command: "require"
    arguments: "twig/twig:~1.0"
    working_dir: "{{ twigc_composer_working_dir }}"

- name: PHPize Twig C extension
  command: phpize
  args:
    chdir: "{{ twigc_composer_working_dir }}/{{ twigc_composer_relative_path }}"
    creates: "{{ twigc_composer_working_dir }}/{{ twigc_composer_relative_path }}/configure"

- name: Configure Twig C extension
  shell: "./configure"
  args:
    chdir: "{{ twigc_composer_working_dir }}/{{ twigc_composer_relative_path }}"
    creates: "{{ twigc_composer_working_dir }}/{{ twigc_composer_relative_path }}/Makefile"

- name: Make the Twig C extension
  command: make
  args:
    chdir: "{{ twigc_composer_working_dir }}/{{ twigc_composer_relative_path }}"
    creates: "{{ twigc_composer_working_dir }}/{{ twigc_composer_relative_path }}/modules/twig.so"

- name: Register PHP's extension dir
  shell: php -i | grep extension_dir | cut -c 18-39
  register: php_extension_dir
  changed_when: False

- name: Install the Twig C extension
  command: make install
  args:
    chdir: "{{ twigc_composer_working_dir }}/{{ twigc_composer_relative_path }}"
    creates: "{{ php_extension_dir.stdout }}/twig.so"

- name: Create twig.ini
  template:
    src: 'twig.ini.j2'
    dest: '/etc/php5/mods-available/twig.ini'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Configure twig.ini for FPM
  file:
    src: "/etc/php5/mods-available/twig.ini"
    dest: "/etc/php5/fpm/conf.d/20-twig.ini"
    state: link
  notify: 'Restart php5-fpm'

- meta: flush_handlers
